<a href="https://colab.research.google.com/github/mmghorbani/Machine_Learning_2024/blob/main/EX1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q5

In [9]:
import numpy as np

# Uppertriangle matrix with zero element
A1 = np.array([[1, 2, 3],[0, 0, 3],[0, 0, 3]])
print(A1)
print('Det = ', np.linalg.det(A1))

# Uppertriangle matrix without zero element
A2 = np.array([[1, 2, 3],[0, 2, 3],[0, 0, 3]])
print(A2)
print('Det = ', np.linalg.det(A2))

[[1 2 3]
 [0 0 3]
 [0 0 3]]
Det =  0.0
[[1 2 3]
 [0 2 3]
 [0 0 3]]
Det =  6.0


# Q6


In [ ]:
import numpy as np
import timeit

m , n = 20, 10

A = np.random.rand(m,n)
k = np.random.rand(n)
p1 = np.zeros(m)
p2 = np.zeros(m)

# Calculate A*p by loop method

for i in range(n):
      p1 += A[:,i] * k[i]


# Calculate A*p by dot method
p2 = np.dot(A,k)


# Check similarity of results
if np.allclose(p1,p2) == True:
    print("Results are same")
else:
    print("Results are different")


# Calculate Time difference
t1 = timeit.timeit("p1", globals=globals())
t2 = timeit.timeit("p2", globals=globals())

print('Time taken by loop method: ', t1)
print('Time taken by dot method: ', t2)
print('Time difference: ', t1-t2)

Results are same
Time taken by loop method:  0.01579736899998352
Time taken by dot method:  0.015628609000032156
Time difference:  0.00016875999995136226
